spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: gemasclashes@gmail.com
    password: zosemwsxaonpbfpi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

