version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: pg-local
    restart: always
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"